language: csharp
dotnet: 2.2
dist: xenial
services:
  - elasticsearch
  
script: 
  - bash ./build.sh -t test

branches:
  only:
    - master
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1