language: csharp
dotnet: 2.2
dist: xenial
services:
  - elasticsearch
  
script: 
  - dotnet restore elastic-studies.sln
  - dotnet build -c Release elastic-studies.sln
  - dotnet test -c Release tests/Tests

branches:
  only:
    - master
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1