image: Visual Studio 2017
install:
  - cinst elasticsearch
  - appveyor-retry elasticsearch-service-x64 start
build_script:
  - build.cmd -t build
test_script:
  - cmd: build.cmd -t test_only
branches:
  only:
    - master
